sudo: required
dist: trusty
language: python
python:
  - 2.7
  - 3.5
  - 3.6
cache: pip
install:
  - pip install -U pip wheel
  - pip install tensorflow==1.3.0rc0
  - pip install --process-dependency-links .
  - pip install .[test]
  - pip install codecov
script:
  - nosetests testing --verbosity=3
after_success:
  - codecov
